
[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  command = "echo 'Static site ready'"
  targetPort = 8888
  port = 8889
  publish = "public"
  autoLaunch = true

[functions]
  directory = "netlify/functions"
