# Konfigurasi Build Utama
[build]
  # Folder yang akan di-deploy ke publik
  publish = "public"
  # Folder tempat functions berada
  functions = "netlify/functions"

# Konfigurasi spesifik untuk Functions (INI KUNCINYA)
[functions]
  # Memberitahu Netlify untuk meng-bundle (menggabungkan) setiap fungsi
  # beserta dependensinya secara terpisah menggunakan esbuild.
  # Ini adalah cara paling modern dan anti-gagal.
  node_bundler = "esbuild"
  
  # Menentukan versi Node.js yang akan digunakan
  # Kita gunakan versi 20, yang modern dan stabil
  [functions.node_compat]
    runtime = "nodejs20.x"

# Aturan Redirect (tetap sama)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
